import pandas as pd
df = pd.read_csv('data/streaming_sim_trades.csv')
print('=== POSITION SIZE ANALYSIS ===')
print(f'Total trades: {len(df):,}')
print(f'Avg shares: {df["shares"].mean():,.0f}')
print(f'Median shares: {df["shares"].median():,.0f}')
print(f'Avg notional: ${df["notional"].mean():,.0f}')
print(f'Median notional: ${df["notional"].median():,.0f}')
print(f'Max notional: ${df["notional"].max():,.0f}')
over1m = (df["notional"] > 1_000_000).sum()
over2m = (df["notional"] > 2_000_000).sum()
over3m = (df["notional"] > 3_000_000).sum()
print(f'Trades with notional > 1M: {over1m:,} ({over1m/len(df)*100:.1f}%)')
print(f'Trades with notional > 2M: {over2m:,} ({over2m/len(df)*100:.1f}%)')
print(f'Trades with notional > 3M: {over3m:,} ({over3m/len(df)*100:.1f}%)')
print(f'Avg leverage: {df["notional"].mean() / 1_000_000:.2f}x')
print(f'Max leverage: {df["notional"].max() / 1_000_000:.2f}x')
print()
print('=== RISK ANALYSIS ===')
print(f'Avg risk_dollars: ${df["risk_dollars"].mean():,.0f}')
print(f'Max risk_dollars: ${df["risk_dollars"].max():,.0f}')
print(f'Avg risk as pct of capital: {df["risk_dollars"].mean() / 1_000_000 * 100:.2f}%')
